# aerospike-config.yaml
#
# Deployment Manager template for deploying Aerospike on a cluster of servers.
#
# The Aerospike deployment here consists of the following replica pool:
#  * Aerospike server instances
#
# A gcp Aerospike replicaset deployment will have 3 Aerospike instances

imports:
- path: aerospike.jinja
- name: default.py
  path: common/default.py
- name: common.py
  path: common/common.py
- name: vm_instance.py
  path: common/vm_instance.py
- name: vm_multiple_instances.py
  path: common/vm_multiple_instances.py

resources:
- name: aerospike_server
  type: aerospike.jinja
  properties:
    # Begin: GCE resource parameters
    numReplicas: 3
    namePrefix: aerospike-cluster
    zone: us-central1-c
    machineType: n1-highmem-4
    network: default
    bootDiskType: pd-standard
    # End: GCE resource parameters

    # Begin: Aerospike resource parameters    
    numLocalSSDs: 1
    useShadowDevice: false
    diskSize: 0

    ## NOTE THAT WE MANUALLY ADDED 500G SSD DRIVE FOR STORAGE OF mlssd and dev-mlssd
    ## THUS THEY ARE COMMENTED OUT HERE. ADD THE SSD DRIVE VIA THE GCP INTERFACE AND THEN UNCOMMENT AND RESTART
    namespace: |
        ## GENERAL NAMESPACE
        namespace gen {
            replication-factor 2
            memory-size 100G
            default-ttl 0d # 30 days, use 0 to never expire/evict.
            storage-engine device {
                device dev/disk/by-id/google-local-ssd-0-part1
                write-block-size 1M
            }
        }
        namespace dev-gen {
            replication-factor 2
            memory-size 10G
            default-ttl 0d
            storage-engine device {
                device /dev/disk/by-id/google-local-ssd-0-part9
                write-block-size 1M
            }
        }

        ## IN MEMORY STORAGE
        namespace ml {
           replication-factor 2
           memory-size 10G
           default-ttl 0d # 30 days, use 0 to never expire/evict.
           storage-engine memory
        }        
        namespace dev-ml {
           replication-factor 2
           memory-size 4G
           default-ttl 0d # 30 days, use 0 to never expire/evict.
           storage-engine memory
        }

        ## MLSSD STORAGE 
        namespace mlssd {
           replication-factor 2
           memory-size 100G 
           default-ttl 0d # 30 days, use 0 to never expire/evict.
           storage-engine device {
              device /dev/disk/by-id/google-local-ssd-0-part5
              write-block-size 1M
           }
        }

        namespace dev-mlssd {
           replication-factor 2
           memory-size 10G 
           default-ttl 0d # 30 days, use 0 to never expire/evict.
           storage-engine device {
              device /dev/disk/by-id/google-local-ssd-0-part7
              write-block-size 1M
           }
        }

        security {
          enable-security true
        }
