# aerospike-config.yaml
#
# Deployment Manager template for deploying Aerospike on a cluster of servers.
#
# The Aerospike deployment here consists of the following replica pool:
#  * Aerospike server instances
#
# A gcp Aerospike replicaset deployment will have 3 Aerospike instances

imports:
- path: aerospike.jinja
- name: default.py
  path: common/default.py
- name: common.py
  path: common/common.py
- name: vm_instance.py
  path: common/vm_instance.py
- name: vm_multiple_instances.py
  path: common/vm_multiple_instances.py

resources:
- name: aerospike_server
  type: aerospike.jinja
  properties:
    # Begin: GCE resource parameters
    numReplicas: 1
    namePrefix: aerospike
    zone: us-central1-b
    machineType: n1-highmem-4
    network: default
    bootDiskType: pd-standard
    # End: GCE resource parameters

    # Begin: Aerospike resource parameters
    numLocalSSDs: 1
    useShadowDevice: false
    diskSize: 0

    namespace: |
        namespace ssd {
            replication-factor 2
            memory-size 25G
            default-ttl 0d # 30 days, use 0 to never expire/evict.
            storage-engine device {
                device /dev/disk/by-id/google-local-ssd-0 # local ssds
                #device /dev/disk/by-id/google-$DISK
                write-block-size 1M
            }
        }
        namespace ml {
           replication-factor 2
           memory-size 4G
           default-ttl 0d # 30 days, use 0 to never expire/evict.
           storage-engine memory
        }

    security: |
      security {
          enable-security true
      }
